/*
 * Dependency-Check Plugin for SonarQube
 * Copyright (C) 2015-2025 dependency-check
 * philipp.dallig@gmail.com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package org.sonar.dependencycheck.rule;

import javax.annotation.ParametersAreNonnullByDefault;

import org.sonar.api.issue.impact.Severity;
import org.sonar.api.issue.impact.SoftwareQuality;
import org.sonar.api.rule.RuleStatus;
import org.sonar.api.rules.RuleType;
import org.sonar.api.server.rule.RulesDefinition;
import org.sonar.api.rules.CleanCodeAttribute;
import org.sonar.dependencycheck.base.DependencyCheckConstants;

public class KnownCveRuleDefinition implements RulesDefinition {

    private static final int CWE_937 = 937;
    private static final int CWE_1035 = 1035;

    @Override
    @ParametersAreNonnullByDefault
    public void define(Context context) {
        NewRepository repo = context.createRepository(DependencyCheckConstants.REPOSITORY_KEY,
                DependencyCheckConstants.LANGUAGE_KEY);
        repo.setName("OWASP");

        NewRule rule = repo.createRule(DependencyCheckConstants.RULE_KEY);
        fillOWASPRule(rule);
        
        NewRule ruleWithSecurityHotspot = repo.createRule(DependencyCheckConstants.RULE_KEY_WITH_SECURITY_HOTSPOT);
        fillOWASPRule(ruleWithSecurityHotspot);
        ruleWithSecurityHotspot.setType(RuleType.SECURITY_HOTSPOT);
        
        repo.done();
    }

    private void fillOWASPRule(NewRule rule) {
        rule.addTags("cwe-937", "cwe-1035", "cwe", "cve", "owasp-2017-a9", "owasp-2021-a6", "security", "vulnerability");
        rule.setName("Vulnerable and Outdated Components");
        rule.setCleanCodeAttribute(CleanCodeAttribute.COMPLETE);
        rule.addDefaultImpact(SoftwareQuality.SECURITY, Severity.MEDIUM);
        rule.setStatus(RuleStatus.READY);
        
        // Add mappings for multiple standard versions to maximize grid compatibility
        rule.addOwaspTop10(OwaspTop10Version.Y2017, OwaspTop10.A9);
        rule.addOwaspTop10(OwaspTop10Version.Y2021, OwaspTop10.A6);
        
        // Explicitly add CWEs that SonarQube uses for the grid mapping
        rule.addCwe(CWE_937, CWE_1035);

        String description = "<p>Components, such as libraries, frameworks, and other software modules, "
                + "almost always run with full privileges. If a vulnerable component is exploited, such "
                + "an attack can facilitate serious data loss or server takeover. Applications using "
                + "components with known vulnerabilities may undermine application defenses and enable "
                + "a range of possible attacks and impacts.</p>"
                + "<h3>References:</h3>"
                + "<ul><li><a href=\"https://owasp.org/www-project-top-ten/2021/A06_2021-Vulnerable_and_Outdated_Components\">OWASP Top 10 2021-A6: Vulnerable and Outdated Components</a></li>"
                + "<li><a href=\"https://owasp.org/www-project-top-ten/2017/A9_2017-Using_Components_with_Known_Vulnerabilities\">OWASP Top 10 2017-A9: Using Components with Known Vulnerabilities</a></li>"
                + "<li><a href=\"https://cwe.mitre.org/data/definitions/937.html\">Common Weakness Enumeration CWE-937</a></li>"
                + "<li><a href=\"https://cwe.mitre.org/data/definitions/1035.html\">Common Weakness Enumeration CWE-1035</a></li></ul>"
                + "<p>This issue was generated by <a href=\"https://www.owasp.org/index.php/OWASP_Dependency_Check\">Dependency-Check</a>";
        rule.setHtmlDescription(description);
    }

}
